# Adicionando o kubernetes
# primeiramente, tenho que criar o cluster com redirecionamento de porta| k3d cluster create meucluster -p "80:30000@loadbalancer"
# agora crio o arquivo manifesto
# agora vai
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  web-page
spec:
  selector:
    matchLabels:
      app: web-page
  template:
    metadata:
      labels:
        app:  web-page
    spec:
      containers:
        - name: site-bem-legal
          image: shuelzin/conversao-temperatura:v1
          ports:
            - containerPort:  8080

---

apiVersion: v1
kind: Service
metadata:
  name: web-page-legal
spec:
  selector:
    app: web-page
  ports:
  - targetPort: 8080
    port: 80
    nodePort: 30000
  type: NodePort